version: 1.0.{build}
os: Visual Studio 2015 RC

environment:
  global:
    APPVEYOR_OS_NAME: windows
  matrix:
  #MSYS2 Building
    - platform: x86
      BUILDER: MSYS2

  #VisualStudio Building
#    - platform: x86
#      BUILDER : VS
#      BITS: 32
    - platform: x64
      BUILDER : VS
      BITS: 64

configuration: Debug
shallow_clone: true
clone_depth: 10

install:
- cd ..
- git clone --depth=1 --branch=master https://github.com/openframeworks/openFrameworks
- call openFrameworks/scripts/ci/addons/install.cmd

build_script:
- call openFrameworks/scripts/ci/addons/build.cmd


